; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Ocal Screen"
#define MyAppVersion "1.0.0 Open Beta"
#define MyAppPublisher "Ocal Software by Gaming Network Studio"
#define MyAppURL "https://gamingnetworkstudio.vercel.app"
#define MyAppExeName "Ocal Screen.exe"
#define MyAppRepository "https://github.com/neelkanth-patel26/Ocal-Screen"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{C8A53B2D-0F9E-4B17-A553-[#2026-OCAL-SCREEN-V100-BETA]}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppRepository}/issues
AppUpdatesURL={#MyAppRepository}/releases
DefaultDirName={autopf}\Ocal Screen
DisableProgramGroupPage=yes
LicenseFile=TERMS_AND_CONDITIONS.md
InfoBeforeFile=PRIVACY_POLICY.md
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=release\installer
OutputBaseFilename=OcalScreen-Setup-v1.0.0-OpenBeta
SetupIconFile=icons\icons\win\icon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "Create a Quick Launch shortcut"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "release\1.5.0\win-unpacked\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
